import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useProducts } from "@/queries/useProducts";
import { useScrollReveal } from "@/hooks/useScrollReveal";
export function ProductsSection() {
    const { data: products, isLoading, error } = useProducts();
    const headerRef = useScrollReveal();
    return (_jsx("section", { id: "produkter", className: "bg-bg-deep py-24 px-6", children: _jsxs("div", { className: "mx-auto max-w-site", children: [_jsxs("div", { ref: headerRef, "data-reveal": true, className: "text-center", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.08em] text-accent font-medium", children: "V\u00E5ra produkter" }), _jsx("h2", { className: "font-serif text-4xl md:text-5xl font-semibold text-ink mt-4", children: "Professionell h\u00E5rv\u00E5rd fr\u00E5n Kevin Murphy" }), _jsx("p", { className: "text-muted text-lg max-w-2xl mx-auto mt-4", children: "Vi anv\u00E4nder och s\u00E4ljer Kevin Murphy \u2013 premiumprodukter som skyddar f\u00E4rg, bygger styrka och bevarar glans. Alla produkter \u00E4r framtagna med h\u00E5llbarhet i fokus och ger l\u00E5ngvariga resultat." })] }), isLoading && (_jsx("p", { className: "text-muted text-sm text-center mt-12", children: "Laddar..." })), error && (_jsx("p", { className: "text-red-500 text-sm text-center mt-12", children: "Kunde inte ladda produkter." })), products && products.length > 0 && (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mt-12", children: products.map((product, index) => (_jsx(ProductCard, { product: product, index: index }, product.id))) }))] }) }));
}
function ProductCard({ product, index, }) {
    const cardRef = useScrollReveal();
    return (_jsx("div", { ref: cardRef, "data-reveal": true, style: { transitionDelay: `${index * 0.08}s` }, children: _jsxs(Card, { hover: true, className: "h-full", children: [_jsx("div", { className: "rounded-md overflow-hidden aspect-[4/3] mb-4", children: _jsx("img", { src: `/assets/${product.image}`, alt: product.name, className: "object-cover w-full h-full", loading: "lazy" }) }), _jsx("h3", { className: "font-serif text-lg font-semibold text-ink", children: product.name }), _jsx("div", { className: "mt-2", children: _jsx(Badge, { variant: "default", children: product.price }) }), _jsx("p", { className: "text-muted text-sm mt-2", children: product.description }), product.features.length > 0 && (_jsx("ul", { className: "mt-3 space-y-1", children: product.features.map((feature) => (_jsxs("li", { className: "text-sm text-muted flex items-start gap-2", children: [_jsx("span", { className: "text-accent mt-0.5", "aria-hidden": "true", children: "\u2022" }), _jsx("span", { children: feature })] }, feature))) }))] }) }));
}
//# sourceMappingURL=ProductsSection.js.map